security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                target: hello

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_USER: []
        ROLE_BANNED: []

    access_control:
        # Accès à /admin seulement pour les ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Accès à /profile seulement pour les ROLE_USER et ROLE_ADMIN
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset, roles: PUBLIC_ACCESS }
