security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider   # Utilisation du provider entity

            form_login:
                login_path: login
                check_path: login

            logout:
                path: logout
                target: home

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]      # ROLE_ADMIN a tous les droits de ROLE_USER
        ROLE_USER: []                # ROLE_USER est le rôle de base
        ROLE_BANNED: []              # ROLE_BANNED a moins de droits

    access_control:
        # Accès à /admin seulement pour les ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Accès à /profile seulement pour les ROLE_USER et ROLE_ADMIN
        - { path: ^/profile, roles: ROLE_USER }
